package main

import (
	"encoding/json"
	"fmt"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
)

//type tag struct {
//	data	map[string]int64
//	tagInfos	tagInfos
//}
//type tagInfos struct {
//	page	int8
//	total	int64
//	tags	interface{}
//	pageSize int32
//}
//type imageStatus struct {
//	status string
//	digest string
//	imageCreate int64
//	imageId	string
//	imageUpdate	int64
//	tag string
//	imageSize	int64
//}

type AutoGenerated struct {
	Data Data `json:"data"`
}
type Tags struct {
	Status      string `json:"status"`
	Digest      string `json:"digest"`
	ImageCreate int64  `json:"imageCreate"`
	ImageID     string `json:"imageId"`
	ImageUpdate int64  `json:"imageUpdate"`
	Tag         string `json:"tag"`
	ImageSize   int    `json:"imageSize"`
}
type Data struct {
	Total    int    `json:"total"`
	Page     int    `json:"page"`
	Tags     []Tags `json:"tags"`
	PageSize int    `json:"pageSize"`
}

func main() {
	client, err := sdk.NewClientWithAccessKey("cn-hangzhou", "LTAI4GKuRVd8TtNift14gvek", "1fvsP63srlqMcZWuJhcLB72IMHgXNw")
	if err != nil {
		panic(err)
	}

	request := requests.NewCommonRequest()
	request.Method = "GET"
	request.Scheme = "https" // https | http
	request.Domain = "cr.cn-hangzhou.aliyuncs.com"
	request.Version = "2016-06-07"
	request.PathPattern = "/repos/guming_teste/book-starter-client/tags"
	request.Headers["Content-Type"] = "application/json"

	body := `{}`
	request.Content = []byte(body)

	response, err := client.ProcessCommonRequest(request)
	if err != nil {
		panic(err)
	}

	tagInfo := response.GetHttpContentString()
	//fmt.Print(tagInfo)
	// 反序列化
	//str := `{"name":"周琳1","age":90}`
	var p2 AutoGenerated
	json.Unmarshal([]byte(tagInfo), &p2) // 传指针是为了能在json.Unmarshal内部修改p2的值

	//fmt.Println(p2)
	for i, _ := range p2.Data.Tags {
		tagVersion := p2.Data.Tags[i].Tag
		fmt.Println(tagVersion)
		if i == 10 {
			break
		}
	}
	//fmt.Println(p2.Data.Tags[0].Tag)

}
